import { c as create_ssr_component, v as validate_component } from "../../../chunks/index2.js";
const Eightfold = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<h2>From Book II of the Yoga Sutras</h2>
<p><a href="${"https://www.gutenberg.org/cache/epub/2526/pg2526-images.html"}" rel="${"nofollow"}">The Yoga Sutras of Patanjali translated by Charles Johnston</a></p>
<p>…</p>
<ol start="${"28"}"><li>From steadfastly following after the means of Yoga, until impurity is worn away, there comes the illumination of thought up to full discernment.</li></ol>
<p>Here, we enter on the more detailed practical teaching of Patanjali, with its sound and luminous good sense. And when we come to detail the means of Yoga, we may well be astonished at their simplicity. There is little in them that is mysterious. They are very familiar. The essence of the matter lies in carrying them out.</p>
<ol start="${"29"}"><li>The eight means of Yoga are: the Commandments, the Rules, right Poise, right Control of the life-force, Withdrawal, Attention, Meditation, Contemplation.</li></ol>
<p>These eight means are to be followed in their order, in the sense which will immediately be made clear. We can get a ready understanding of the first two by comparing them with the Commandments which must be obeyed by all good citizens, and the Rules which are laid on the members of religious orders. Until one has fulfilled the first, it is futile to concern oneself with the second. And so with all the means of Yoga. They must be taken in their order.</p>
<ol start="${"30"}"><li>The Commandments are these: nom injury, truthfulness, abstaining from stealing, from impurity, from covetousness.</li></ol>
<p>These five precepts are almost exactly the same as the Buddhist Commandments: not to kill, not to steal, not to be guilty of incontinence, not to drink intoxicants, to speak the truth. Almost identical is St. Paul’s list: Thou shalt not commit adultery, thou shalt not kill, thou shalt not steal, thou shalt not covet. And in the same spirit is the answer made to the young map having great possessions, who asked, What shall I do to be saved? and received the reply: Keep the Commandments.</p>
<p>This broad, general training, which forms and develops human character, must be accomplished to a very considerable degree, before there can be much hope of success in the further stages of spiritual life. First the psychical, and then the spiritual. First the man, then the angel. On this broad, humane and wise foundation does the system of Patanjali rest.</p>
<ol start="${"31"}"><li>The Commandments, not limited to any race, place, time or occasion, universal, are the great obligation.</li></ol>
<p>The Commandments form the broad general training of humanity. Each one of them rests on a universal, spiritual law. Each one of them expresses an attribute or aspect of the Self, the Eternal; when we violate one of the Commandments, we set ourselves against the law and being of the Eternal, thereby bringing ourselves to inevitable con fusion. So the first steps in spiritual life must be taken by bringing ourselves into voluntary obedience to these spiritual laws and thus making ourselves partakers of the spiritual powers, the being of the Eternal Like the law of gravity, the need of air to breathe, these great laws know no exceptions They are in force in all lands, throughout al times, for all mankind.</p>
<ol start="${"32"}"><li>The Rules are these: purity, serenity fervent aspiration, spiritual reading, and per feet obedience to the Master.</li></ol>
<p>Here we have a finer law, one which humanity as a whole is less ready for, less fit to obey. Yet we can see that these Rules are the same in essence as the Commandments, but on a higher, more spiritual plane. The Commandments may be obeyed in outer acts and abstinences; the Rules demand obedience of the heart and spirit, a far more awakened and more positive consciousness. The Rules are the spiritual counterpart of the Commandments, and they have finer degrees, for more advanced spiritual growth.</p>
<ol start="${"33"}"><li>When transgressions hinder, the weight of the imagination should be thrown’ on the opposite side.</li></ol>
<p>Let us take a simple case, that of a thief, a habitual criminal, who has drifted into stealing in childhood, before the moral consciousness has awakened. We may imprison such a thief, and deprive him of all possibility of further theft, or of using the divine gift of will. Or we may recognize his disadvantages, and help him gradually to build up possessions which express his will, and draw forth his self-respect. If we imagine that, after he has built well, and his possessions have become dear to him, he himself is robbed, then we can see how he would come vividly to realize the essence of theft and of honesty, and would cleave to honest dealings with firm conviction. In some such way does the great Law teach us. Our sorrows and losses teach us the pain of the sorrow and loss we inflict on others, and so we cease to inflict them.</p>
<p>Now as to the more direct application. To conquer a sin, let heart and mind rest, not on the sin, but on the contrary virtue. Let the sin be forced out by positive growth in the true direction, not by direct opposition. Turn away from the sin and go forward courageously, constructively, creatively, in well-doing. In this way the whole nature will gradually be drawn up to the higher level, on which the sin does not even exist. The conquest of a sin is a matter of growth and evolution, rather than of opposition.</p>
<ol start="${"34"}"><li>Transgressions are injury, falsehood, theft, incontinence, envy; whether committed, or caused, or assented to, through greed, wrath, or infatuation; whether faint, or middling, or excessive; bearing endless, fruit of ignorance and pain. Therefore must the weight be cast on the other side.</li></ol>
<p>Here are the causes of sin: greed, wrath, infatuation, with their effects, ignorance and pain. The causes are to be cured by better wisdom, by a truer understanding of the Self, of Life. For greed cannot endure before the realization that the whole world belongs to the Self, which Self we are; nor can we hold wrath against one who is one with the Self, and therefore with ourselves; nor can infatuation, which is the seeking for the happiness of the All in some limited part of it, survive the knowledge that we are heirs of the All. Therefore let thought and imagination, mind and heart, throw their weight on the other side; the side, not of the world, but of the Self.</p>
<ol start="${"35"}"><li>Where non-injury is perfected, all enmity ceases in the presence of him who possesses it.</li></ol>
<p>We come now to the spiritual powers which result from keeping the Commandments; from the obedience to spiritual law which is the keeping of the Commandments. Where the heart is full of kindness which seeks no injury to another, either in act or thought or wish, this full love creates an atmosphere of harmony, whose benign power touches with healing all who come within its influence. Peace in the heart radiates peace to other hearts, even more surely than contention breeds contention.</p>
<ol start="${"36"}"><li>When he is perfected in truth, all acts and their fruits depend on him.</li></ol>
<p>The commentator thus explains: If he who has attained should say to a man, Become righteous! the man becomes righteous. If he should say, Gain heaven! the man gains heaven. His word is not in vain.</p>
<p>Exactly the same doctrine was taught by the Master who said to his disciples: Receive ye the Holy Ghost: whose soever sins ye remit they are remitted unto them; and whose soever sins ye retain, they are retained.</p>
<ol start="${"37"}"><li>Where cessation from theft is perfected, all treasures present themselves to him who possesses it.</li></ol>
<p>Here is a sentence which may warn us that, beside the outer and apparent meaning, there is in many of these sentences a second and finer significance. The obvious meaning is, that he who has wholly ceased from theft, in act, thought and wish, finds buried treasures in his path, treasures of jewels and gold and pearls. The deeper truth is, that he who in every least thing is wholly honest with the spirit of Life, finds Life supporting him in all things, and gains admittance to the treasure house of Life, the spiritual universe.</p>
<ol start="${"38"}"><li>For him who is perfect in continence, the reward is valour and virility.</li></ol>
<p>The creative power, strong and full of vigour, is no longer dissipated, but turned to spiritual uses. It upholds and endows the spiritual man, conferring on him the creative will, the power to engender spiritual children instead of bodily progeny. An epoch of life, that of man the animal, has come to an end; a new epoch, that of the spiritual man, is opened. The old creative power is superseded and transcended; a new creative power, that of the spiritual man, takes its place, carrying with it the power to work creatively in others for righteousness and eternal life.</p>
<p>One of the commentaries says that he who has attained is able to transfer to the minds of his disciples what he knows concerning divine union, and the means of gaining it. This is one of the powers of purity.</p>
<ol start="${"39"}"><li>Where there is firm conquest of covetousness, he who has conquered it awakes to the how and why of life.</li></ol>
<p>So it is said that, before we can understand the laws of Karma, we must free ourselves from Karma. The conquest of covetousness brings this rich fruit, because the root of covetousness is the desire of the individual soul, the will toward manifested life. And where the desire of the individual soul is overcome by the superb, still life of the universal Soul welling up in the heart within, the great secret is discerned, the secret that the individual soul is not an isolated reality, but the ray, the manifest instrument of the Life, which turns it this way and that until the great work is accomplished, the age-long lesson learned. Thus is the how and why of life disclosed by ceasing from covetousness. The Commentator says that this includes a knowledge of one’s former births.</p>
<ol start="${"40"}"><li>Through purity a withdrawal from one’s own bodily life, a ceasing from infatuation with the bodily life of others.</li></ol>
<p>As the spiritual light grows in the heart within, as the taste for pure Life grows stronger, the consciousness opens toward the great, secret places within, where all life is one, where all lives are one. Thereafter, this outer, manifested, fugitive life, whether of ourselves or of others, loses something of its charm and glamour, and we seek rather the deep infinitudes. Instead of the outer form and surroundings of our lives, we long for their inner and everlasting essence. We desire not so much outer converse and closeness to our friends, but rather that quiet communion with them in the inner chamber of the soul, where spirit speaks to spirit, and spirit answers; where alienation and separation never enter; where sickness and sorrow and death cannot come.</p>
<ol start="${"41"}"><li>To the pure of heart come also a quiet spirit, one-pointed thought, the victory over sensuality, and fitness to behold the Soul.</li></ol>
<p>Blessed are the pure in heart, for they shall see God, who is the supreme Soul; the ultimate Self of all beings. In the deepest sense, purity means fitness for this vision, and also a heart cleansed from all disquiet, from all wandering and unbridled thought, from the torment of sensuous imaginings; and when the spirit is thus cleansed and pure, it becomes at one in essence with its source, the great Spirit, the primal Life. One consciousness now thrills through both, for the psychic partition wall is broken down. Then shall the pure in heart see God, because they become God.</p>
<ol start="${"42"}"><li>From acceptance, the disciple gains happiness supreme.</li></ol>
<p>One of the wise has said: accept conditions, accept others, accept yourself. This is the true acceptance, for all these things are what they are through the will of the higher Self, except their deficiencies, which come through thwarting the will of the higher Self, and can be conquered only through compliance with that will. By the true acceptance, the disciple comes into oneness of spirit with the overruling Soul; and, since the own nature of the Soul is being, happiness, bliss, he comes thereby into happiness supreme.</p>
<ol start="${"43"}"><li>The perfection of the powers of the bodily vesture comes through the wearing away of impurities, and through fervent aspiration.</li></ol>
<p>This is true of the physical powers, and of those which dwell in the higher vestures. There must be, first, purity; as the blood must be pure, before one can attain to physical health. But absence of impurity is not in itself enough, else would many nerveless ascetics of the cloisters rank as high saints. There is needed, further, a positive fire of the will; a keen vital vigour for the physical powers, and something finer, purer, stronger, but of kindred essence, for the higher powers. The fire of genius is something more than a phrase, for there can be no genius without the celestial fire of the awakened spiritual will.</p>
<ol start="${"44"}"><li>Through spiritual reading, the disciple gains communion with the divine Power on which his heart is set.</li></ol>
<p>Spiritual reading meant, for ancient India, something more than it does with us. It meant, first, the recital of sacred texts, which, in their very sounds, had mystical potencies; and it meant a recital of texts which were divinely emanated, and held in themselves the living, potent essence of the divine.</p>
<p>For us, spiritual reading means a communing with the recorded teachings of the Masters of wisdom, whereby we read ourselves into the Master’s mind, just as through his music one can enter into the mind and soul of the master musician. It has been well said that all true art is contagion of feeling; so that through the true reading of true books we do indeed read ourselves into the spirit of the Masters, share in the atmosphere of their wisdom and power, and come at last into their very presence.</p>
<ol start="${"45"}"><li>Soul-vision is perfected through perfect obedience to the Master.</li></ol>
<p>The sorrow and darkness of life come of the erring personal will which sets itself against the will of the Soul, the one great Life. The error of the personal will is inevitable, since each will must be free to choose, to try and fail, and so to find the path. And sorrow and darkness are inevitable, until the path be found, and the personal will made once more one with the greater Will, wherein it finds rest and power, without losing freedom. In His will is our peace. And with that peace comes light. Soul-vision is perfected through obedience.</p>
<ol start="${"46"}"><li>Right poise must be firm and without strain.</li></ol>
<p>Here we approach a section of the teaching which has manifestly a two-fold meaning. The first is physical, and concerns the bodily position of the student, and the regulation of breathing. These things have their direct influence upon soul-life, the life of the spiritual man, since it is always and everywhere true that our study demands a sound mind in a sound body. The present sentence declares that, for work and for meditation, the position of the body must be steady and without strain, in order that the finer currents of life may run their course.</p>
<p>It applies further to the poise of the soul, that fine balance and stability which nothing can shake, where the consciousness rests on the firm foundation of spiritual being. This is indeed the house set upon a rock, which the winds and waves beat upon in vain.</p>
<ol start="${"47"}"><li>Right poise is to be gained by steady and temperate effort, and by setting the heart upon the everlasting.</li></ol>
<p>Here again, there is the two-fold meaning, for physical poise is to be gained by steady effort of the muscles, by gradual and wise training, linked with a right understanding of, and relation with, the universal force of gravity. Uprightness of body demands that both these conditions shall be fulfilled.</p>
<p>In like manner the firm and upright poise of the spiritual man is to be gained by steady and continued effort, always guided by wisdom, and by setting the heart on the Eternal, filling the soul with the atmosphere of the spiritual world. Neither is effective without the other. Aspiration without effort brings weakness; effort without aspiration brings a false strength, not resting on enduring things. The two together make for the right poise which sets the spiritual man firmly and steadfastly on his feet.</p>
<ol start="${"48"}"><li>The fruit of right poise is the strength to resist the shocks of infatuation or sorrow.</li></ol>
<p>In the simpler physical sense, which is also coveted by the wording of the original, this sentence means that wise effort establishes such bodily poise that the accidents of life cannot disturb it, as the captain remains steady, though disaster overtake his ship.</p>
<p>But the deeper sense is far more important. The spiritual man, too, must learn to withstand all shocks, to remain steadfast through the perturbations of external things and the storms and whirlwinds of the psychical world. This is the power which is gained by wise, continuous effort, and by filling the spirit with the atmosphere of the Eternal.</p>
<ol start="${"49"}"><li>When this is gained, there follows the right guidance of the life-currents, the control of the incoming and outgoing breath.</li></ol>
<p>It is well understood to-day that most of our maladies come from impure conditions of the blood. It is coming to be understood that right breathing, right oxygenation, will do very much to keep the blood clean and pure. Therefore a right knowledge of breathing is a part of the science of life.</p>
<p>But the deeper meaning is, that the spiritual man, when he has gained poise through right effort and aspiration, can stand firm, and guide the currents of his life, both the incoming current of events, and the outgoing current of his acts.</p>
<p>Exactly the same symbolism is used in the saying: Not that which goeth into the mouth defileth a man; but that which cometh out of the mouth, this defileth a man…. Those things which proceed out of the mouth come forth from the heart … out of the heart proceed evil thoughts, murders, uncleanness, thefts, false witness, blasphemies. Therefore the first step in purification is to keep the Commandments.</p>
<ol start="${"50"}"><li>The life-current is either outward, or inward, or balanced; it is regulated according to place, time, number; it is prolonged and subtle.</li></ol>
<p>The technical, physical side of this has its value. In the breath, there should be right inbreathing, followed by the period of pause, when the air comes into contact with the blood, and this again followed by right outbreathing, even, steady, silent. Further, the lungs should be evenly filled; many maladies may arise from the neglect and consequent weakening of some region of the lungs. And the number of breaths is so important, so closely related to health, that every nurse’s chart records it.</p>
<p>But the deeper meaning is concerned with the currents of life; with that which goeth into and cometh out of the heart.</p>
<ol start="${"51"}"><li>The fourth degree transcends external and internal objects.</li></ol>
<p>The inner meaning seems to be that, in addition to the three degrees of control already described, control, that is, over the incoming current of life, over the outgoing current, and over the condition of pause or quiesence, there is a fourth degree of control, which holds in complete mastery both the outer passage of events and the inner currents of thoughts and emotions; a condition of perfect poise and stability in the midst of the flux of things outward and inward.</p>
<ol start="${"52"}"><li>Thereby is worn away the veil which covers up the light.</li></ol>
<p>The veil is the psychic nature, the web of emotions, desires, argumentative trains of thought, which cover up and obscure the truth by absorbing the entire attention and keeping the consciousness in the psychic realm. When hopes and fears are reckoned at their true worth, in comparison with lasting possessions of the Soul; when the outer reflections of things have ceased to distract us from inner realities; when argumentative-thought no longer entangles us, but yields its place to flashing intuition, the certainty which springs from within; then is the veil worn away, the consciousness is drawn from the psychical to the spiritual, from the temporal to the Eternal. Then is the light unveiled.</p>
<ol start="${"53"}"><li>Thence comes the mind’s power to hold itself in the light.</li></ol>
<p>It has been well said, that what we most need is the faculty of spiritual attention; and in the same direction of thought it has been eloquently declared that prayer does not consist in our catching God’s attention, but rather in our allowing God to hold our attention.</p>
<p>The vital matter is, that we need to disentangle our consciousness from the noisy and perturbed thraldom of the psychical, and to come to consciousness as the spiritual man. This we must do, first, by purification, through the Commandments and the Rules; and, second, through the faculty of spiritual attention, by steadily heeding endless fine intimations of the spiritual power within us, and by intending our consciousness thereto; thus by degrees transferring the centre of consciousness from the psychical to the spiritual. It is a question, first, of love, and then of attention.</p>
<ol start="${"54"}"><li>The right Withdrawal is the disengaging of the powers from entanglement in outer things, as the psychic nature has been withdrawn and stilled.</li></ol>
<p>To understand this, let us reverse the process, and think of the one consciousness, centred in the Soul, gradually expanding and taking on the form of the different perceptive powers; the one will, at the same time, differentiating itself into the varied powers of action.</p>
<p>Now let us imagine this to be reversed, so that the spiritual force, which has gone into the differentiated powers, is once more gathered together into the inner power of intuition and spiritual will, taking on that unity which is the hall-mark of spiritual things, as diversity is the seal of material things.</p>
<p>It is all a matter of love for the quality of spiritual consciousness, as against psychical consciousness, of love and attention. For where the heart is, there will the treasure be also; where the consciousness is, there will the vesture with its powers be developed.</p>
<ol start="${"55"}"><li>Thereupon follows perfect mastery over the powers.</li></ol>
<p>When the spiritual condition which we have described is reached, with its purity, poise, and illuminated vision, the spiritual man is coming into his inheritance, and gaining complete mastery of his powers.</p>
<p>Indeed, much of the struggle to keep the Commandments and the Rules has been paving the way for this mastery; through this very struggle and sacrifice the mastery has become possible; just as, to use St. Paul’s simile, the athlete gains the mastery in the contest and the race through the sacrifice of his long and arduous training. Thus he gains the crown.</p>
<h2>From Book III of the Yoga Sutras</h2>
<ol><li>The binding of the perceiving consciousness to a certain region is attention (dharana).</li></ol>
<p>Emerson quotes Sir Isaac Newton as saying that he made his great discoveries by intending his mind on them. That is what is meant here. I read the page of a book while inking of something else. At the end of he page, I have no idea of what it is about, and read it again, still thinking of something else, with the same result. Then I wake up, so to speak, make an effort of attention, fix my thought on what I am reading, and easily take in its meaning. The act of will, the effort of attention, the intending of the mind on each word and line of the page, just as the eyes are focussed on each word and line, is the power here contemplated. It is the power to focus the consciousness on a given spot, and hold it there Attention is the first and indispensable step in all knowledge. Attention to spiritual things is the first step to spiritual knowledge.</p>
<ol start="${"2"}"><li>A prolonged holding of the perceiving consciousness in that region is meditation (dhyana).</li></ol>
<p>This will apply equally to outer and inner things. I may for a moment fix my attention on some visible object, in a single penetrating glance, or I may hold the attention fixedly on it until it reveals far more of its nature than a single glance could perceive. The first is the focussing of the searchlight of consciousness upon the object. The other is the holding of the white beam of light steadily and persistently on the object, until it yields up the secret of its details. So for things within; one may fix the inner glance for a moment on spiritual things, or one may hold the consciousness steadily upon them, until what was in the dark slowly comes forth into the light, and yields up its immortal secret. But this is possible only for the spiritual man, after the Commandments and the Rules have been kept; for until this is done, the thronging storms of psychical thoughts dissipate and distract the attention, so that it will not remain fixed on spiritual things. The cares of this world, the deceitfulness of riches, choke the word of the spiritual message.</p>
<ol start="${"3"}"><li>When the perceiving consciousness in this meditative is wholly given to illuminating the essential meaning of the object contemplated, and is freed from the sense of separateness and personality, this is contemplation (samadhi).</li></ol>
<p>Let us review the steps so far taken. First, the beam of perceiving consciousness is focussed on a certain region or subject, through the effort of attention. Then this attending consciousness is held on its object. Third, there is the ardent will to know its meaning, to illumine it with comprehending thought. Fourth, all personal bias—all desire merely to indorse a previous opinion and so prove oneself right, and all desire for personal profit or gratification must be quite put away. There must be a purely disinterested love of truth for its own sake. Thus is the perceiving consciousness made void, as it were, of all personality or sense of separateness. The personal limitation stands aside and lets the All-consciousness come to bear upon the problem. The Oversoul bends its ray upon the object, and illumines it with pure light.</p>
<ol start="${"4"}"><li>When these three, Attention, Meditation Contemplation, are exercised at once, this is perfectly concentrated Meditation (sanyama).</li></ol>
<p>When the personal limitation of the perceiving consciousness stands aside, and allows the All-conscious to come to bear upon the problem, then arises that real knowledge which is called a flash of genius; that real knowledge which makes discoveries, and without which no discovery can be made, however painstaking the effort. For genius is the vision of the spiritual man, and that vision is a question of growth rather than present effort; though right effort, rightly continued, will in time infallibly lead to growth and vision. Through the power thus to set aside personal limitation, to push aside petty concerns and cares, and steady the whole nature and will in an ardent love of truth and desire to know it; through the power thus to make way for the All-consciousness, all great men make their discoveries. Newton, watching the apple fall to the earth, was able to look beyond, to see the subtle waves of force pulsating through apples and worlds and suns and galaxies, and thus to perceive universal gravitation. The Oversoul, looking through his eyes, recognized the universal force, one of its own children. Darwin, watching the forms and motions of plants and animals, let the same august consciousness come to bear on them, and saw infinite growth perfected through ceaseless struggle. He perceived the superb process of evolution, the Oversoul once more recognizing its own. Fraunhofer, noting the dark lines in the band of sunlight in his spectroscope, divined their identity with the bright lines in the spectra of incandescent iron, sodium and the rest, and so saw the oneness of substance in the worlds and suns, the unity of the materials of the universe. Once again the Oversoul, looking with his eyes, recognized its own. So it is with all true knowledge. But the mind must transcend its limitations, its idiosyncrasies; there must be purity, for to the pure in heart is the promise, that they shall see God.</p>
<ol start="${"5"}"><li>By mastering this perfectly concentrated Meditation, there comes the illumination of perception.</li></ol>
<p>The meaning of this is illustrated by what has been said before. When the spiritual man is able to throw aside the trammels of emotional and mental limitation, and to open his eyes, he sees clearly, he attains to illuminated perception. A poet once said that Occultism is the conscious cultivation of genius; and it is certain that the awakened spiritual man attains to the perceptions of genius. Genius is the vision, the power, of the spiritual man, whether its possessor recognizes this or not. All true knowledge is of the spiritual man. The greatest in all ages have recognized this and put their testimony on record. The great in wisdom who have not consciously recognized it, have ever been full of the spirit of reverence, of selfless devotion to truth, of humility, as was Darwin; and reverence and humility are the unconscious recognition of the nearness of the Spirit, that Divinity which broods over us, a Master o’er a slave.</p>
<p>…</p>
<p><a href="${"https://www.gutenberg.org/cache/epub/2526/pg2526-images.html"}" rel="${"nofollow"}">The Yoga Sutras of Patanjali translated by Charles Johnston</a></p>`;
});
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<article class="${"prose p-4 lg:prose-xl dark:prose-invert prose-li:text-blue "}">${validate_component(Eightfold, "EightFold").$$render($$result, {}, {}, {})}</article>`;
});
export {
  Page as default
};
